### ISSUE TITLE
Demande de vérification

### ISSUE THREAD

**Issue by Omegzbug** [PolytechLyon/2019-isi3-graph-vial-ganne#7]
Nous avons finis le TP. Nous voulions avoir vos retour.

**Comment by Slashgear** [comment]
- [ ] Rapport non complet ⚠️ Relisez les question. Il manque les graph et les réponses sont un peu rapides.
- ⚠️ Les packages en Java sont toujours en minuscules
- Trouvez le souci dans ces quelques lignes

https://github.com/PolytechLyon/2019-isi3-graph-vial-ganne/blob/1e80d58ceac20a34ed83a9a1d2d0ba16cc8aff37/src/main/java/graph/DirectedGraph.java#L47-L51

- 👍 Pour l'iterateur

**Comment by Slashgear** [comment]
Vous ne m'avez pas répondu entièrement

> Trouvez le souci dans ces quelques lignes
```java
 public Set<Node> getAllNodes(){ 
 	HashSet<Node> allNodes = new HashSet<>(adjacence.keySet()); 
 	return allNodes; 
  
 } 
```

**Comment by Omegzbug** [comment]
Étrange, nous avons pourtant modifié la fonction de la sorte:
	public Set<Node> getAllNodes(){
		return adjacence.keySet();
	}
